package client;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import java.util.List;

/**
 * The Class Game. Contains all the informations of current game, API for server communication and simple HTML client.
 */
public class Game {
	
	/** The server URL. */
	private String serverURL;
	
	/** The player id. */
	private String playerId = "";
	
	/** The game id. */
	private String gameId = "";
	
	/**
	 * Instantiates a new game.
	 *
	 * @param serverURL the server URL
	 */
	public Game(String serverURL) {
		super();
		setServerURL(serverURL);
	}
	
	/**
	 * Sets the game id.
	 *
	 * @param gameId the new game id
	 */
	private void setGameId(String gameId) {
		this.gameId = gameId;
	}
	
	/**
	 * Sets the server URL.
	 *
	 * @param serverURL the new server URL
	 */
	private void setServerURL(String serverURL) {
		this.serverURL = serverURL;
	}

	/**
	 * Sets the player id.
	 *
	 * @param playerId the player's unique id (UUID)
	 */
	private void setPlayerId(String playerId) {
		this.playerId = playerId;
	}

	/**
	 * Start.
	 *
	 * @param name the player's name
	 * @return the string. Error generated by server, or null if successful.
	 * @throws IOException Signals that an I/O exception has occurred.
	 */
	public String start(String name) throws IOException {
		try {
			ServerResponse sr = getResponse("?playerName=" + name);
			List<String> errorHeader = sr.getHeaders().getOrDefault("ERROR", null);
			if(errorHeader != null)	return errorHeader.get(0);
			else {
				List<String> gameHeader = sr.getHeaders().getOrDefault("gameId", null);
				setGameId(gameHeader.get(0));
				List<String> playerHeader = sr.getHeaders().getOrDefault("playerId", null);
				setPlayerId(playerHeader.get(0));
				return null;				
			}
		} catch (NullPointerException e) {
			e.printStackTrace();
			return null;
		}
	}
	
	/**
	 * Play. Contains basic API for communication with the server.
	 *
	 * @param column the column for disk insertion.
	 * @return the server response object.
	 * @throws IOException Signals that an I/O exception has occurred.
	 */
	public ServerResponse play(int column) throws IOException {
		return getResponse("/play?gameId=" + gameId + "&playerId=" + playerId + "&command=" + String.valueOf(column));
	}

	/**
	 * Gets the response from server defined in ServerURL + command generated by play and start functions. 
	 *
	 * @param the command for server
	 * @return the responseServer object
	 * @throws IOException Signals that an I/O exception has occurred.
	 */
	private ServerResponse getResponse(String command) throws IOException {
		ServerResponse servResponse = new ServerResponse();
		StringBuilder body = new StringBuilder();
		URL fiveInRow = new URL(serverURL + command);
		URLConnection fir = fiveInRow.openConnection();
		BufferedReader in = new BufferedReader(
				new InputStreamReader(
						fir.getInputStream()));
		String inputLine;
		while ((inputLine = in.readLine()) != null) {
			body.append(inputLine);
		}
		servResponse.setBody(body.toString());
		servResponse.setHeaders(fir.getHeaderFields());
		in.close();
		return servResponse;
	}


}
